POST https://linguistic-murial-adventist-university-of-central-afri-7975ce32.koyeb.app/api/accounts/users/
Content-Type: "application/json"
{
    "full_name": "John Doe",
    "email": "john.doe@example.com",
    "password": "securepassword123",
    "re_password": "securepassword123",
    "bio": "Software developer with a passion for open-source projects.",
    "role": "CLIENT",
    "phone_number": "+1234567890"
}

###

POST https://linguistic-murial-adventist-university-of-central-afri-7975ce32.koyeb.app/api/accounts/users/
Content-Type: application/json

{
    "full_name": "Jane Smith",
    "email": "jane.smith@example.com",
    "password": "anotherpassword456",
    "re_password": "anotherpassword456",
    "bio": "Product manager interested in African tech innovations.",
    "role": "VENDOR",
    "phone_number": "+9876543210"
}

###

POST https://linguistic-murial-adventist-university-of-central-afri-7975ce32.koyeb.app/api/accounts/users/
Content-Type: application/json

{
    "full_name": "Ahmed Hassan",
    "email": "ahmed.hassan@example.com",
    "password": "hashedpass789",
    "re_password": "hashedpass789",
    "bio": "Marketing executive focused on digital transformation.",
    "role": "ADMIN",
    "phone_number": "+1122334455"
}