### Cash In (Deposit)
POST {{baseUrl}}/payments/cashin/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": 1000,
  "phone_number": "250781234567"
}

### Cash Out (Withdrawal)
POST {{baseUrl}}/payments/cashout/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": 500,
  "phone_number": "250781234567"
}
